ALTER SCHEMA `my_site`  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `article` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `abstract` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `update_time` INT(11) NULL DEFAULT NULL,
  `create_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `article`
ADD COLUMN `status` SMALLINT(6) NULL DEFAULT NULL AFTER `content`;
CHANGE COLUMN `status` `status` SMALLINT(6) NULL DEFAULT 3 ;



CREATE TABLE IF NOT EXISTS `author` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` VARCHAR(125) NULL DEFAULT NULL,
  `birthplace` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE `author`
CHANGE COLUMN `id` `id` BIGINT(20) NOT NULL AUTO_INCREMENT ;


CREATE TABLE IF NOT EXISTS `account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `identity` VARCHAR(125) NOT NULL,
  `password` VARCHAR(125) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `info` JSON NULL,
  `status` SMALLINT(6) NULL DEFAULT 2,
  `create_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;